# Generated by Django 2.2.14 on 2021-02-09 17:06

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone1',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
