# Generated by Django 2.2.14 on 2021-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210221_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone1',
            field=models.IntegerField(default=0),
        ),
    ]
