# Generated by Django 2.2.14 on 2021-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiloapp', '0005_auto_20210206_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, null=True, to='kiloapp.Post')),
            ],
        ),
    ]
