# Generated by Django 2.2.14 on 2021-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='n/a', max_length=50)),
                ('cover', models.ImageField(default='/images/no.png', upload_to='images/')),
            ],
        ),
    ]
