# Generated by Django 2.2.14 on 2021-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food',
            field=models.CharField(choices=[('Biriyani', 'Biriyani'), ('Curries', 'Curries'), ('Garlic Rice', 'Garlic Rice'), ('Juice Bar', 'Juice Bar'), ('Kilo koththu', 'Kilo koththu')], default='Biriyani', max_length=15),
        ),
    ]
