# Generated by Django 2.2.14 on 2021-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0002_post_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spacial',
            field=models.BooleanField(default=False),
        ),
    ]
