# Generated by Django 2.2.14 on 2021-02-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0003_post_spacial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
