# Generated by Django 2.2.14 on 2021-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0004_auto_20210203_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food',
            field=models.CharField(choices=[('Biriyani', 'Biriyani'), ('Curries', 'Curries'), ('Garlic Rice', 'Garlic Rice'), ('Juice Bar', 'Juice Bar'), ('Kilo koththu', 'Kilo koththu')], default='Juice Bar', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
