# Generated by Django 2.2.14 on 2021-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0005_auto_20210206_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='kiloapp/images/logo.jpeg', upload_to='images/'),
        ),
    ]
