# Generated by Django 2.2.14 on 2021-02-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiloapp', '0006_auto_20210222_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
